<?php

return [
    'models' => [
        ['name' => 'Audi A1', 'label' => 'Audi A1', 'multiplier' => 1.0],
        ['name' => 'Audi A4', 'label' => 'Audi A4', 'multiplier' => 1.1],
        ['name' => 'Audi Q7', 'label' => 'Audi Q7', 'multiplier' => 1.5],
        ['name' => 'Audi e-tron', 'label' => 'Audi e-tron (Elektro SUV)', 'multiplier' => 1.5],
        ['name' => 'Audi RS3', 'label' => 'Audi RS3 (Sporta)', 'multiplier' => 1.3],
        ['name' => 'Audi RS4', 'label' => 'Audi RS4 (Sporta)', 'multiplier' => 1.4],
        ['name' => 'Audi RS6', 'label' => 'Audi RS6 (Sporta)', 'multiplier' => 1.6],
        ['name' => 'Audi S3', 'label' => 'Audi S3 (Sporta)', 'multiplier' => 1.2],
        ['name' => 'Audi S5', 'label' => 'Audi S5 (Sporta)', 'multiplier' => 1.3],
        ['name' => 'BMW 1 Series', 'label' => 'BMW 1 Series (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'BMW 2 Series', 'label' => 'BMW 2 Series (Kupeja)', 'multiplier' => 1.1],
        ['name' => 'BMW 3 Series', 'label' => 'BMW 3 Series (Sedans)', 'multiplier' => 1.1],
        ['name' => 'BMW 4 Series', 'label' => 'BMW 4 Series (Kupeja)', 'multiplier' => 1.2],
        ['name' => 'BMW 5 Series', 'label' => 'BMW 5 Series (Lielā)', 'multiplier' => 1.3],
        ['name' => 'BMW 6 Series', 'label' => 'BMW 6 Series (Gran Turismo)', 'multiplier' => 1.4],
        ['name' => 'BMW 7 Series', 'label' => 'BMW 7 Series (Premium sedans)', 'multiplier' => 1.5],
        ['name' => 'BMW 8 Series', 'label' => 'BMW 8 Series (Luksusa kupeja)', 'multiplier' => 1.6],
        ['name' => 'BMW X1', 'label' => 'BMW X1 (Mazais SUV)', 'multiplier' => 1.1],
        ['name' => 'BMW X2', 'label' => 'BMW X2 (Krosovers)', 'multiplier' => 1.2],
        ['name' => 'BMW X3', 'label' => 'BMW X3 (SUV)', 'multiplier' => 1.3],
        ['name' => 'BMW X4', 'label' => 'BMW X4 (Sporta SUV)', 'multiplier' => 1.4],
        ['name' => 'BMW X5', 'label' => 'BMW X5 (Lielais SUV)', 'multiplier' => 1.5],
        ['name' => 'BMW X6', 'label' => 'BMW X6 (Kupeja SUV)', 'multiplier' => 1.6],
        ['name' => 'BMW X7', 'label' => 'BMW X7 (Premium SUV)', 'multiplier' => 1.7],
        ['name' => 'BMW Z4', 'label' => 'BMW Z4 (Roadsters)', 'multiplier' => 1.4],
        ['name' => 'BMW i3', 'label' => 'BMW i3 (Elektro kompakts)', 'multiplier' => 1.1],
        ['name' => 'BMW i4', 'label' => 'BMW i4 (Elektro sedans)', 'multiplier' => 1.3],
        ['name' => 'BMW iX', 'label' => 'BMW iX (Elektro SUV)', 'multiplier' => 1.6],
        ['name' => 'BMW iX3', 'label' => 'BMW iX3 (Elektro SUV)', 'multiplier' => 1.4],
        ['name' => 'BMW M2', 'label' => 'BMW M2 (Sporta)', 'multiplier' => 1.4],
        ['name' => 'BMW M3', 'label' => 'BMW M3 (Sporta)', 'multiplier' => 1.5],
        ['name' => 'BMW M4', 'label' => 'BMW M4 (Sporta kupeja)', 'multiplier' => 1.5],
        ['name' => 'BMW M5', 'label' => 'BMW M5 (Sporta sedans)', 'multiplier' => 1.6],
        ['name' => 'BMW M8', 'label' => 'BMW M8 (Luksusa sporta)', 'multiplier' => 1.8],
        ['name' => 'Mercedes A-Class', 'label' => 'Mercedes A-Class (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'Mercedes B-Class', 'label' => 'Mercedes B-Class (Kompakts minivens)', 'multiplier' => 1.1],
        ['name' => 'Mercedes C-Class', 'label' => 'Mercedes C-Class (Sedans)', 'multiplier' => 1.2],
        ['name' => 'Mercedes CLA', 'label' => 'Mercedes CLA (Sporta sedans)', 'multiplier' => 1.2],
        ['name' => 'Mercedes E-Class', 'label' => 'Mercedes E-Class (Lielais sedans)', 'multiplier' => 1.3],
        ['name' => 'Mercedes CLS', 'label' => 'Mercedes CLS (Luksusa kupeja)', 'multiplier' => 1.4],
        ['name' => 'Mercedes S-Class', 'label' => 'Mercedes S-Class (Premium sedans)', 'multiplier' => 1.5],
        ['name' => 'Mercedes GLA', 'label' => 'Mercedes GLA (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Mercedes GLB', 'label' => 'Mercedes GLB (Kompakts SUV)', 'multiplier' => 1.3],
        ['name' => 'Mercedes GLC', 'label' => 'Mercedes GLC (SUV)', 'multiplier' => 1.4],
        ['name' => 'Mercedes GLE', 'label' => 'Mercedes GLE (Lielais SUV)', 'multiplier' => 1.5],
        ['name' => 'Mercedes GLS', 'label' => 'Mercedes GLS (Premium SUV)', 'multiplier' => 1.6],
        ['name' => 'Mercedes G-Class', 'label' => 'Mercedes G-Class (Apvidus auto)', 'multiplier' => 1.7],
        ['name' => 'Mercedes EQA', 'label' => 'Mercedes EQA (Elektro SUV)', 'multiplier' => 1.3],
        ['name' => 'Mercedes EQB', 'label' => 'Mercedes EQB (Elektro SUV)', 'multiplier' => 1.4],
        ['name' => 'Mercedes EQC', 'label' => 'Mercedes EQC (Elektro SUV)', 'multiplier' => 1.5],
        ['name' => 'Mercedes EQE', 'label' => 'Mercedes EQE (Elektro sedans)', 'multiplier' => 1.5],
        ['name' => 'Mercedes EQS', 'label' => 'Mercedes EQS (Elektro luksuss sedans)', 'multiplier' => 1.6],
        ['name' => 'Mercedes Vito', 'label' => 'Mercedes Vito (Mikroautobuss)', 'multiplier' => 1.7],
        ['name' => 'Mercedes V-Class', 'label' => 'Mercedes V-Class (Premium busiņš)', 'multiplier' => 1.8],
        ['name' => 'Mercedes Sprinter', 'label' => 'Mercedes Sprinter (Kravas/vienības busiņš)', 'multiplier' => 2.0],
        ['name' => 'Mercedes AMG A45', 'label' => 'Mercedes AMG A45 (Sporta kompakts)', 'multiplier' => 1.4],
        ['name' => 'Mercedes AMG C63', 'label' => 'Mercedes AMG C63 (Sporta sedans)', 'multiplier' => 1.6],
        ['name' => 'Mercedes AMG E63', 'label' => 'Mercedes AMG E63 (Sporta luksus sedans)', 'multiplier' => 1.7],
        ['name' => 'Mercedes AMG GTR', 'label' => 'Mercedes AMG GTR (Superauto)', 'multiplier' => 2.0],
        ['name' => 'Volkswagen Up!', 'label' => 'Volkswagen Up! (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Volkswagen Polo', 'label' => 'Volkswagen Polo (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'Volkswagen Golf', 'label' => 'Volkswagen Golf (Vidēja klase)', 'multiplier' => 1.1],
        ['name' => 'Volkswagen Golf Variant', 'label' => 'Volkswagen Golf Variant (Universālis)', 'multiplier' => 1.2],
        ['name' => 'Volkswagen Jetta', 'label' => 'Volkswagen Jetta (Sedans)', 'multiplier' => 1.2],
        ['name' => 'Volkswagen Passat', 'label' => 'Volkswagen Passat (Lielā klase)', 'multiplier' => 1.3],
        ['name' => 'Volkswagen Passat Variant', 'label' => 'Volkswagen Passat Variant (Universālis)', 'multiplier' => 1.4],
        ['name' => 'Volkswagen Arteon', 'label' => 'Volkswagen Arteon (Premium kupejsedans)', 'multiplier' => 1.4],
        ['name' => 'Volkswagen Tiguan', 'label' => 'Volkswagen Tiguan (SUV)', 'multiplier' => 1.3],
        ['name' => 'Volkswagen Tiguan Allspace', 'label' => 'Volkswagen Tiguan Allspace (SUV ar 7 vietām)', 'multiplier' => 1.4],
        ['name' => 'Volkswagen T-Roc', 'label' => 'Volkswagen T-Roc (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Volkswagen T-Cross', 'label' => 'Volkswagen T-Cross (Kompakts SUV)', 'multiplier' => 1.1],
        ['name' => 'Volkswagen Taigo', 'label' => 'Volkswagen Taigo (Kompakts kupeja SUV)', 'multiplier' => 1.1],
        ['name' => 'Volkswagen Touareg', 'label' => 'Volkswagen Touareg (Lielais SUV)', 'multiplier' => 1.5],
        ['name' => 'Volkswagen Touran', 'label' => 'Volkswagen Touran (Ģimenes minivens)', 'multiplier' => 1.4],
        ['name' => 'Volkswagen Sharan', 'label' => 'Volkswagen Sharan (Lielais minivens)', 'multiplier' => 1.5],
        ['name' => 'Volkswagen Caddy', 'label' => 'Volkswagen Caddy (Mazais kravas/vienības auto)', 'multiplier' => 1.6],
        ['name' => 'Volkswagen Transporter T5', 'label' => 'Volkswagen Transporter T5 (Busiņš)', 'multiplier' => 1.7],
        ['name' => 'Volkswagen Transporter T6', 'label' => 'Volkswagen Transporter T6 (Busiņš)', 'multiplier' => 1.7],
        ['name' => 'Volkswagen Multivan', 'label' => 'Volkswagen Multivan (Premium busiņš)', 'multiplier' => 1.8],
        ['name' => 'Volkswagen ID.3', 'label' => 'Volkswagen ID.3 (Elektro kompakts)', 'multiplier' => 1.2],
        ['name' => 'Volkswagen ID.4', 'label' => 'Volkswagen ID.4 (Elektro SUV)', 'multiplier' => 1.3],
        ['name' => 'Volkswagen ID.5', 'label' => 'Volkswagen ID.5 (Elektro kupeja SUV)', 'multiplier' => 1.4],
        ['name' => 'Volkswagen ID.Buzz', 'label' => 'Volkswagen ID.Buzz (Elektro retro busiņš)', 'multiplier' => 1.6],
        ['name' => 'Toyota Aygo', 'label' => 'Toyota Aygo (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Toyota Yaris', 'label' => 'Toyota Yaris (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'Toyota Yaris Cross', 'label' => 'Toyota Yaris Cross (Mazais SUV)', 'multiplier' => 1.1],
        ['name' => 'Toyota Corolla', 'label' => 'Toyota Corolla (Sedans/Hatchback)', 'multiplier' => 1.1],
        ['name' => 'Toyota Corolla Touring Sports', 'label' => 'Toyota Corolla Touring Sports (Universālis)', 'multiplier' => 1.2],
        ['name' => 'Toyota Prius', 'label' => 'Toyota Prius (Hibrīda sedans)', 'multiplier' => 1.2],
        ['name' => 'Toyota Camry', 'label' => 'Toyota Camry (Lielais sedans)', 'multiplier' => 1.3],
        ['name' => 'Toyota Avensis', 'label' => 'Toyota Avensis (Sedans/Universālis)', 'multiplier' => 1.3],
        ['name' => 'Toyota C-HR', 'label' => 'Toyota C-HR (Kompakts SUV)', 'multiplier' => 1.2],
        ['name' => 'Toyota RAV4', 'label' => 'Toyota RAV4 (SUV)', 'multiplier' => 1.3],
        ['name' => 'Toyota Highlander', 'label' => 'Toyota Highlander (Lielais SUV)', 'multiplier' => 1.5],
        ['name' => 'Toyota Land Cruiser', 'label' => 'Toyota Land Cruiser (Apvidus auto)', 'multiplier' => 1.6],
        ['name' => 'Toyota Hilux', 'label' => 'Toyota Hilux (Pikaps)', 'multiplier' => 1.6],
        ['name' => 'Toyota Proace City', 'label' => 'Toyota Proace City (Mazais komercauto)', 'multiplier' => 1.5],
        ['name' => 'Toyota Proace Verso', 'label' => 'Toyota Proace Verso (Mikroautobuss)', 'multiplier' => 1.7],
        ['name' => 'Toyota GR Yaris', 'label' => 'Toyota GR Yaris (Sporta kompakts)', 'multiplier' => 1.3],
        ['name' => 'Toyota Supra', 'label' => 'Toyota Supra (Sporta kupeja)', 'multiplier' => 1.6],
        ['name' => 'Toyota bZ4X', 'label' => 'Toyota bZ4X (Elektro SUV)', 'multiplier' => 1.4],
        ['name' => 'Nissan Micra', 'label' => 'Nissan Micra (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'Nissan Note', 'label' => 'Nissan Note (Mazais ģimenes auto)', 'multiplier' => 1.1],
        ['name' => 'Nissan Leaf', 'label' => 'Nissan Leaf (Elektro sedans)', 'multiplier' => 1.2],
        ['name' => 'Nissan Juke', 'label' => 'Nissan Juke (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Nissan Qashqai', 'label' => 'Nissan Qashqai (SUV)', 'multiplier' => 1.3],
        ['name' => 'Nissan X-Trail', 'label' => 'Nissan X-Trail (Lielāks SUV)', 'multiplier' => 1.4],
        ['name' => 'Nissan Ariya', 'label' => 'Nissan Ariya (Elektro SUV)', 'multiplier' => 1.5],
        ['name' => 'Nissan Navara', 'label' => 'Nissan Navara (Pikaps)', 'multiplier' => 1.6],
        ['name' => 'Nissan Pathfinder', 'label' => 'Nissan Pathfinder (Apvidus auto)', 'multiplier' => 1.6],
        ['name' => 'Nissan Townstar', 'label' => 'Nissan Townstar (Mazais busiņš)', 'multiplier' => 1.5],
        ['name' => 'Nissan Primastar', 'label' => 'Nissan Primastar (Mikroautobuss)', 'multiplier' => 1.7],
        ['name' => 'Škoda Citigo', 'label' => 'Škoda Citigo (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Škoda Fabia', 'label' => 'Škoda Fabia (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'Škoda Scala', 'label' => 'Škoda Scala (Hečbeks)', 'multiplier' => 1.1],
        ['name' => 'Škoda Rapid', 'label' => 'Škoda Rapid (Sedans)', 'multiplier' => 1.1],
        ['name' => 'Škoda Octavia', 'label' => 'Škoda Octavia (Sedans/Universālis)', 'multiplier' => 1.2],
        ['name' => 'Škoda Superb', 'label' => 'Škoda Superb (Lielais sedans)', 'multiplier' => 1.3],
        ['name' => 'Škoda Kamiq', 'label' => 'Škoda Kamiq (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Škoda Karoq', 'label' => 'Škoda Karoq (SUV)', 'multiplier' => 1.3],
        ['name' => 'Škoda Kodiaq', 'label' => 'Škoda Kodiaq (Lielais SUV)', 'multiplier' => 1.5],
        ['name' => 'Škoda Enyaq iV', 'label' => 'Škoda Enyaq iV (Elektro SUV)', 'multiplier' => 1.5],
        ['name' => 'Volvo C30', 'label' => 'Volvo C30 (Kompakts kupejs)', 'multiplier' => 1.1],
        ['name' => 'Volvo S40', 'label' => 'Volvo S40 (Mazais sedans)', 'multiplier' => 1.2],
        ['name' => 'Volvo S60', 'label' => 'Volvo S60 (Vidējs sedans)', 'multiplier' => 1.3],
        ['name' => 'Volvo S80', 'label' => 'Volvo S80 (Lielais sedans)', 'multiplier' => 1.4],
        ['name' => 'Volvo S90', 'label' => 'Volvo S90 (Premium sedans)', 'multiplier' => 1.5],
        ['name' => 'Volvo V40', 'label' => 'Volvo V40 (Universālis)', 'multiplier' => 1.2],
        ['name' => 'Volvo V60', 'label' => 'Volvo V60 (Universālis)', 'multiplier' => 1.3],
        ['name' => 'Volvo V70', 'label' => 'Volvo V70 (Lielais universālis)', 'multiplier' => 1.4],
        ['name' => 'Volvo V90', 'label' => 'Volvo V90 (Premium universālis)', 'multiplier' => 1.5],
        ['name' => 'Volvo XC40', 'label' => 'Volvo XC40 (Mazais SUV)', 'multiplier' => 1.3],
        ['name' => 'Volvo XC60', 'label' => 'Volvo XC60 (SUV)', 'multiplier' => 1.4],
        ['name' => 'Volvo XC70', 'label' => 'Volvo XC70 (Apvidus universālis)', 'multiplier' => 1.5],
        ['name' => 'Volvo XC90', 'label' => 'Volvo XC90 (Lielais SUV)', 'multiplier' => 1.6],
        ['name' => 'Volvo EX30', 'label' => 'Volvo EX30 (Elektro SUV)', 'multiplier' => 1.3],
        ['name' => 'Volvo EX90', 'label' => 'Volvo EX90 (Elektro premium SUV)', 'multiplier' => 1.6],
        ['name' => 'Honda Jazz', 'label' => 'Honda Jazz (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Honda Civic', 'label' => 'Honda Civic (Sedans/Hečbeks)', 'multiplier' => 1.1],
        ['name' => 'Honda Accord', 'label' => 'Honda Accord (Vidējs sedans)', 'multiplier' => 1.3],
        ['name' => 'Honda Insight', 'label' => 'Honda Insight (Hibrīds sedans)', 'multiplier' => 1.2],
        ['name' => 'Honda HR-V', 'label' => 'Honda HR-V (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Honda CR-V', 'label' => 'Honda CR-V (SUV)', 'multiplier' => 1.4],
        ['name' => 'Honda e', 'label' => 'Honda e (Elektro kompakts)', 'multiplier' => 1.1],
        ['name' => 'Honda Prelude', 'label' => 'Honda Prelude (Kupeja)', 'multiplier' => 1.3],
        ['name' => 'Honda S2000', 'label' => 'Honda S2000 (Roadsters)', 'multiplier' => 1.4],
        ['name' => 'Honda Odyssey', 'label' => 'Honda Odyssey (Minivens)', 'multiplier' => 1.5],
        ['name' => 'Ford Fiesta', 'label' => 'Ford Fiesta (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'Ford Focus', 'label' => 'Ford Focus (Hečbeks/Sedans)', 'multiplier' => 1.1],
        ['name' => 'Ford Mondeo', 'label' => 'Ford Mondeo (Lielais sedans)', 'multiplier' => 1.3],
        ['name' => 'Ford Fusion', 'label' => 'Ford Fusion (Sedans)', 'multiplier' => 1.2],
        ['name' => 'Ford Mustang', 'label' => 'Ford Mustang (Sporta kupeja)', 'multiplier' => 1.5],
        ['name' => 'Ford Puma', 'label' => 'Ford Puma (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Ford Kuga', 'label' => 'Ford Kuga (SUV)', 'multiplier' => 1.3],
        ['name' => 'Ford Edge', 'label' => 'Ford Edge (Lielais SUV)', 'multiplier' => 1.4],
        ['name' => 'Ford Explorer', 'label' => 'Ford Explorer (Premium SUV)', 'multiplier' => 1.5],
        ['name' => 'Ford EcoSport', 'label' => 'Ford EcoSport (Mazais SUV)', 'multiplier' => 1.1],
        ['name' => 'Ford Ranger', 'label' => 'Ford Ranger (Pikaps)', 'multiplier' => 1.6],
        ['name' => 'Ford Tourneo Connect', 'label' => 'Ford Tourneo Connect (Mazais busiņš)', 'multiplier' => 1.5],
        ['name' => 'Ford Transit Custom', 'label' => 'Ford Transit Custom (Vidējs busiņš)', 'multiplier' => 1.7],
        ['name' => 'Ford Transit', 'label' => 'Ford Transit (Lielais komercauto)', 'multiplier' => 1.8],
        ['name' => 'Mazda 2', 'label' => 'Mazda 2 (Mazais kompakts)', 'multiplier' => 1.0],
        ['name' => 'Mazda 3', 'label' => 'Mazda 3 (Hečbeks/Sedans)', 'multiplier' => 1.1],
        ['name' => 'Mazda 6', 'label' => 'Mazda 6 (Vidējs sedans/universālis)', 'multiplier' => 1.3],
        ['name' => 'Mazda CX-3', 'label' => 'Mazda CX-3 (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Mazda CX-30', 'label' => 'Mazda CX-30 (Kompakts SUV)', 'multiplier' => 1.3],
        ['name' => 'Mazda CX-5', 'label' => 'Mazda CX-5 (SUV)', 'multiplier' => 1.4],
        ['name' => 'Mazda CX-60', 'label' => 'Mazda CX-60 (Plug-in hibrīds SUV)', 'multiplier' => 1.5],
        ['name' => 'Mazda CX-9', 'label' => 'Mazda CX-9 (Lielais SUV)', 'multiplier' => 1.6],
        ['name' => 'Mazda MX-5', 'label' => 'Mazda MX-5 (Sporta roadsters)', 'multiplier' => 1.3],
        ['name' => 'Mazda MX-30', 'label' => 'Mazda MX-30 (Elektro SUV)', 'multiplier' => 1.3],
        ['name' => 'Kia Picanto', 'label' => 'Kia Picanto (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Kia Rio', 'label' => 'Kia Rio (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'Kia Ceed', 'label' => 'Kia Ceed (Hečbeks/Universālis)', 'multiplier' => 1.1],
        ['name' => 'Kia Proceed', 'label' => 'Kia Proceed (Sporta universālis)', 'multiplier' => 1.2],
        ['name' => 'Kia Stonic', 'label' => 'Kia Stonic (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Kia Sportage', 'label' => 'Kia Sportage (SUV)', 'multiplier' => 1.4],
        ['name' => 'Kia Sorento', 'label' => 'Kia Sorento (Lielais SUV)', 'multiplier' => 1.6],
        ['name' => 'Kia Niro', 'label' => 'Kia Niro (Hibrīds/elektro SUV)', 'multiplier' => 1.3],
        ['name' => 'Kia EV6', 'label' => 'Kia EV6 (Elektro kupeja SUV)', 'multiplier' => 1.5],
        ['name' => 'Kia Carens', 'label' => 'Kia Carens (Ģimenes minivens)', 'multiplier' => 1.4],
        ['name' => 'Kia Carnival', 'label' => 'Kia Carnival (Lielais minivens)', 'multiplier' => 1.7],
        ['name' => 'Hyundai i10', 'label' => 'Hyundai i10 (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Hyundai i20', 'label' => 'Hyundai i20 (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'Hyundai i30', 'label' => 'Hyundai i30 (Hečbeks/Universālis)', 'multiplier' => 1.1],
        ['name' => 'Hyundai Elantra', 'label' => 'Hyundai Elantra (Sedans)', 'multiplier' => 1.2],
        ['name' => 'Hyundai Sonata', 'label' => 'Hyundai Sonata (Vidējs sedans)', 'multiplier' => 1.3],
        ['name' => 'Hyundai Bayon', 'label' => 'Hyundai Bayon (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Hyundai Kona', 'label' => 'Hyundai Kona (SUV / arī elektro)', 'multiplier' => 1.3],
        ['name' => 'Hyundai Tucson', 'label' => 'Hyundai Tucson (SUV)', 'multiplier' => 1.4],
        ['name' => 'Hyundai Santa Fe', 'label' => 'Hyundai Santa Fe (Lielais SUV)', 'multiplier' => 1.5],
        ['name' => 'Hyundai Palisade', 'label' => 'Hyundai Palisade (Premium SUV)', 'multiplier' => 1.6],
        ['name' => 'Hyundai Ioniq', 'label' => 'Hyundai Ioniq (Hibrīds/elektro)', 'multiplier' => 1.3],
        ['name' => 'Hyundai Ioniq 5', 'label' => 'Hyundai Ioniq 5 (Elektro kupeja SUV)', 'multiplier' => 1.5],
        ['name' => 'Hyundai Ioniq 6', 'label' => 'Hyundai Ioniq 6 (Elektro sedans)', 'multiplier' => 1.6],
        ['name' => 'Peugeot 108', 'label' => 'Peugeot 108 (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Peugeot 208', 'label' => 'Peugeot 208 (Kompakts)', 'multiplier' => 1.1],
        ['name' => 'Peugeot 308', 'label' => 'Peugeot 308 (Hečbeks/Universālis)', 'multiplier' => 1.2],
        ['name' => 'Peugeot 508', 'label' => 'Peugeot 508 (Lielais sedans)', 'multiplier' => 1.3],
        ['name' => 'Peugeot 2008', 'label' => 'Peugeot 2008 (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Peugeot 3008', 'label' => 'Peugeot 3008 (SUV)', 'multiplier' => 1.4],
        ['name' => 'Peugeot 5008', 'label' => 'Peugeot 5008 (SUV ar 7 vietām)', 'multiplier' => 1.5],
        ['name' => 'Peugeot Rifter', 'label' => 'Peugeot Rifter (Minivens/busiņš)', 'multiplier' => 1.5],
        ['name' => 'Peugeot Traveller', 'label' => 'Peugeot Traveller (Lielais busiņš)', 'multiplier' => 1.7],
        ['name' => 'Peugeot e-208', 'label' => 'Peugeot e-208 (Elektro kompakts)', 'multiplier' => 1.2],
        ['name' => 'Peugeot e-2008', 'label' => 'Peugeot e-2008 (Elektro SUV)', 'multiplier' => 1.3],
        ['name' => 'Opel Karl', 'label' => 'Opel Karl (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Opel Corsa', 'label' => 'Opel Corsa (Kompakts)', 'multiplier' => 1.1],
        ['name' => 'Opel Astra', 'label' => 'Opel Astra (Hečbeks/Universālis)', 'multiplier' => 1.2],
        ['name' => 'Opel Insignia', 'label' => 'Opel Insignia (Sedans/Universālis)', 'multiplier' => 1.3],
        ['name' => 'Opel Crossland', 'label' => 'Opel Crossland (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Opel Mokka', 'label' => 'Opel Mokka (SUV)', 'multiplier' => 1.3],
        ['name' => 'Opel Grandland', 'label' => 'Opel Grandland (Vidējs SUV)', 'multiplier' => 1.4],
        ['name' => 'Opel Combo Life', 'label' => 'Opel Combo Life (Minivens)', 'multiplier' => 1.5],
        ['name' => 'Opel Zafira Life', 'label' => 'Opel Zafira Life (Mikroautobuss)', 'multiplier' => 1.6],
        ['name' => 'Renault Twingo', 'label' => 'Renault Twingo (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Renault Clio', 'label' => 'Renault Clio (Kompakts)', 'multiplier' => 1.1],
        ['name' => 'Renault Captur', 'label' => 'Renault Captur (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Renault Megane', 'label' => 'Renault Megane (Hečbeks/Universālis)', 'multiplier' => 1.2],
        ['name' => 'Renault Arkana', 'label' => 'Renault Arkana (Kupeja SUV)', 'multiplier' => 1.3],
        ['name' => 'Renault Austral', 'label' => 'Renault Austral (SUV)', 'multiplier' => 1.3],
        ['name' => 'Renault Koleos', 'label' => 'Renault Koleos (Lielais SUV)', 'multiplier' => 1.5],
        ['name' => 'Renault Scenic', 'label' => 'Renault Scenic (Ģimenes minivens)', 'multiplier' => 1.4],
        ['name' => 'Renault Espace', 'label' => 'Renault Espace (Lielais minivens)', 'multiplier' => 1.5],
        ['name' => 'Renault Kangoo', 'label' => 'Renault Kangoo (Mazais busiņš)', 'multiplier' => 1.5],
        ['name' => 'Renault Trafic', 'label' => 'Renault Trafic (Mikroautobuss)', 'multiplier' => 1.7],
        ['name' => 'Renault Master', 'label' => 'Renault Master (Kravas auto)', 'multiplier' => 1.9],
        ['name' => 'Renault Zoe', 'label' => 'Renault Zoe (Elektro kompakts)', 'multiplier' => 1.2],
        ['name' => 'Tesla Model 3', 'label' => 'Tesla Model 3 (Elektro sedans)', 'multiplier' => 1.4],
        ['name' => 'Tesla Model Y', 'label' => 'Tesla Model Y (Elektro SUV)', 'multiplier' => 1.5],
        ['name' => 'Tesla Model S', 'label' => 'Tesla Model S (Luksusa elektro sedans)', 'multiplier' => 1.6],
        ['name' => 'Tesla Model X', 'label' => 'Tesla Model X (Luksusa elektro SUV)', 'multiplier' => 1.7],
        ['name' => 'Tesla Cybertruck', 'label' => 'Tesla Cybertruck (Pikaps)', 'multiplier' => 2.0],
        ['name' => 'Citroën C1', 'label' => 'Citroën C1 (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Citroën C3', 'label' => 'Citroën C3 (Kompakts)', 'multiplier' => 1.1],
        ['name' => 'Citroën C3 Aircross', 'label' => 'Citroën C3 Aircross (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Citroën C4', 'label' => 'Citroën C4 (Hečbeks)', 'multiplier' => 1.2],
        ['name' => 'Citroën ë-C4', 'label' => 'Citroën ë-C4 (Elektro hečbeks)', 'multiplier' => 1.3],
        ['name' => 'Citroën C5 X', 'label' => 'Citroën C5 X (Universālis/SUV)', 'multiplier' => 1.4],
        ['name' => 'Citroën C5 Aircross', 'label' => 'Citroën C5 Aircross (SUV)', 'multiplier' => 1.4],
        ['name' => 'Citroën Berlingo', 'label' => 'Citroën Berlingo (Mazais busiņš)', 'multiplier' => 1.5],
        ['name' => 'Citroën Spacetourer', 'label' => 'Citroën Spacetourer (Mikroautobuss)', 'multiplier' => 1.7],
        ['name' => 'Lexus CT 200h', 'label' => 'Lexus CT 200h (Hibrīds kompakts)', 'multiplier' => 1.2],
        ['name' => 'Lexus IS', 'label' => 'Lexus IS (Vidējs sedans)', 'multiplier' => 1.3],
        ['name' => 'Lexus ES', 'label' => 'Lexus ES (Lielais sedans)', 'multiplier' => 1.4],
        ['name' => 'Lexus GS', 'label' => 'Lexus GS (Premium sedans)', 'multiplier' => 1.4],
        ['name' => 'Lexus LS', 'label' => 'Lexus LS (Luksusa sedans)', 'multiplier' => 1.6],
        ['name' => 'Lexus NX', 'label' => 'Lexus NX (SUV)', 'multiplier' => 1.4],
        ['name' => 'Lexus RX', 'label' => 'Lexus RX (Premium SUV)', 'multiplier' => 1.5],
        ['name' => 'Lexus UX', 'label' => 'Lexus UX (Kompakts SUV)', 'multiplier' => 1.3],
        ['name' => 'Lexus GX', 'label' => 'Lexus GX (Lielais SUV)', 'multiplier' => 1.6],
        ['name' => 'Lexus LX', 'label' => 'Lexus LX (Flagmanis SUV)', 'multiplier' => 1.7],
        ['name' => 'Mitsubishi Space Star', 'label' => 'Mitsubishi Space Star (Mazais auto)', 'multiplier' => 1.0],
        ['name' => 'Mitsubishi Colt', 'label' => 'Mitsubishi Colt (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'Mitsubishi Lancer', 'label' => 'Mitsubishi Lancer (Sedans)', 'multiplier' => 1.2],
        ['name' => 'Mitsubishi ASX', 'label' => 'Mitsubishi ASX (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Mitsubishi Eclipse Cross', 'label' => 'Mitsubishi Eclipse Cross (SUV)', 'multiplier' => 1.3],
        ['name' => 'Mitsubishi Outlander', 'label' => 'Mitsubishi Outlander (SUV / Plug-in)', 'multiplier' => 1.4],
        ['name' => 'Mitsubishi Pajero', 'label' => 'Mitsubishi Pajero (Apvidus auto)', 'multiplier' => 1.6],
        ['name' => 'Mitsubishi L200', 'label' => 'Mitsubishi L200 (Pikaps)', 'multiplier' => 1.6],
        ['name' => 'Jeep Renegade', 'label' => 'Jeep Renegade (Mazais SUV)', 'multiplier' => 1.3],
        ['name' => 'Jeep Compass', 'label' => 'Jeep Compass (SUV)', 'multiplier' => 1.4],
        ['name' => 'Jeep Cherokee', 'label' => 'Jeep Cherokee (SUV)', 'multiplier' => 1.5],
        ['name' => 'Jeep Grand Cherokee', 'label' => 'Jeep Grand Cherokee (Premium SUV)', 'multiplier' => 1.6],
        ['name' => 'Jeep Wrangler', 'label' => 'Jeep Wrangler (Apvidus auto)', 'multiplier' => 1.6],
        ['name' => 'Jeep Gladiator', 'label' => 'Jeep Gladiator (Pikaps)', 'multiplier' => 1.7],
        ['name' => 'Jeep Avenger', 'label' => 'Jeep Avenger (Mazs elektro SUV)', 'multiplier' => 1.3],
        ['name' => 'Subaru Justy', 'label' => 'Subaru Justy (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'Subaru Impreza', 'label' => 'Subaru Impreza (Hečbeks/Sedans)', 'multiplier' => 1.1],
        ['name' => 'Subaru Legacy', 'label' => 'Subaru Legacy (Sedans/Universālis)', 'multiplier' => 1.3],
        ['name' => 'Subaru Outback', 'label' => 'Subaru Outback (Universālis/SUV)', 'multiplier' => 1.4],
        ['name' => 'Subaru XV (Crosstrek)', 'label' => 'Subaru XV (Mazais SUV)', 'multiplier' => 1.3],
        ['name' => 'Subaru Forester', 'label' => 'Subaru Forester (SUV)', 'multiplier' => 1.4],
        ['name' => 'Subaru Ascent', 'label' => 'Subaru Ascent (Lielais SUV)', 'multiplier' => 1.5],
        ['name' => 'Subaru BRZ', 'label' => 'Subaru BRZ (Sporta kupeja)', 'multiplier' => 1.4],
        ['name' => 'Fiat Panda', 'label' => 'Fiat Panda (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Fiat 500', 'label' => 'Fiat 500 (Retro kompakts)', 'multiplier' => 1.0],
        ['name' => 'Fiat 500X', 'label' => 'Fiat 500X (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Fiat Punto', 'label' => 'Fiat Punto (Kompakts)', 'multiplier' => 1.1],
        ['name' => 'Fiat Tipo', 'label' => 'Fiat Tipo (Sedans/Universālis)', 'multiplier' => 1.2],
        ['name' => 'Fiat Doblo', 'label' => 'Fiat Doblo (Mazais busiņš)', 'multiplier' => 1.5],
        ['name' => 'Fiat Scudo', 'label' => 'Fiat Scudo (Komercauto)', 'multiplier' => 1.6],
        ['name' => 'Fiat Ducato', 'label' => 'Fiat Ducato (Lielais kravas busiņš)', 'multiplier' => 1.8],
        ['name' => 'SEAT Mii', 'label' => 'SEAT Mii (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'SEAT Ibiza', 'label' => 'SEAT Ibiza (Kompakts)', 'multiplier' => 1.0],
        ['name' => 'SEAT Leon', 'label' => 'SEAT Leon (Hečbeks/Universālis)', 'multiplier' => 1.2],
        ['name' => 'SEAT Toledo', 'label' => 'SEAT Toledo (Sedans)', 'multiplier' => 1.2],
        ['name' => 'SEAT Arona', 'label' => 'SEAT Arona (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'SEAT Ateca', 'label' => 'SEAT Ateca (SUV)', 'multiplier' => 1.3],
        ['name' => 'SEAT Tarraco', 'label' => 'SEAT Tarraco (Lielais SUV)', 'multiplier' => 1.5],
        ['name' => 'Suzuki Alto', 'label' => 'Suzuki Alto (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Suzuki Swift', 'label' => 'Suzuki Swift (Kompakts)', 'multiplier' => 1.1],
        ['name' => 'Suzuki Baleno', 'label' => 'Suzuki Baleno (Hečbeks)', 'multiplier' => 1.1],
        ['name' => 'Suzuki Ignis', 'label' => 'Suzuki Ignis (Mazais SUV)', 'multiplier' => 1.2],
        ['name' => 'Suzuki Vitara', 'label' => 'Suzuki Vitara (SUV)', 'multiplier' => 1.3],
        ['name' => 'Suzuki SX4', 'label' => 'Suzuki SX4 (Kompakts SUV)', 'multiplier' => 1.3],
        ['name' => 'Suzuki S-Cross', 'label' => 'Suzuki S-Cross (SUV)', 'multiplier' => 1.4],
        ['name' => 'Suzuki Jimny', 'label' => 'Suzuki Jimny (Apvidus auto)', 'multiplier' => 1.3],
        ['name' => 'Suzuki Grand Vitara', 'label' => 'Suzuki Grand Vitara (Lielāks SUV)', 'multiplier' => 1.5],
        ['name' => 'Chevrolet Spark', 'label' => 'Chevrolet Spark (Mazais auto)', 'multiplier' => 1.0],
        ['name' => 'Chevrolet Aveo', 'label' => 'Chevrolet Aveo (Kompakts)', 'multiplier' => 1.1],
        ['name' => 'Chevrolet Cruze', 'label' => 'Chevrolet Cruze (Sedans)', 'multiplier' => 1.2],
        ['name' => 'Chevrolet Malibu', 'label' => 'Chevrolet Malibu (Vidējs sedans)', 'multiplier' => 1.3],
        ['name' => 'Chevrolet Trax', 'label' => 'Chevrolet Trax (Mazais SUV)', 'multiplier' => 1.3],
        ['name' => 'Chevrolet Captiva', 'label' => 'Chevrolet Captiva (SUV)', 'multiplier' => 1.4],
        ['name' => 'Chevrolet Equinox', 'label' => 'Chevrolet Equinox (Vidējs SUV)', 'multiplier' => 1.4],
        ['name' => 'Chevrolet Tahoe', 'label' => 'Chevrolet Tahoe (Lielais SUV)', 'multiplier' => 1.6],
        ['name' => 'Chevrolet Suburban', 'label' => 'Chevrolet Suburban (XL SUV)', 'multiplier' => 1.7],
        ['name' => 'Chevrolet Camaro', 'label' => 'Chevrolet Camaro (Muscle car)', 'multiplier' => 1.5],
        ['name' => 'Chevrolet Corvette', 'label' => 'Chevrolet Corvette (Sporta kupeja)', 'multiplier' => 1.6],
        ['name' => 'Chrysler 200', 'label' => 'Chrysler 200 (Vidējs sedans)', 'multiplier' => 1.3],
        ['name' => 'Chrysler 300', 'label' => 'Chrysler 300 (Lielais sedans)', 'multiplier' => 1.4],
        ['name' => 'Chrysler PT Cruiser', 'label' => 'Chrysler PT Cruiser (Retro auto)', 'multiplier' => 1.2],
        ['name' => 'Chrysler Pacifica', 'label' => 'Chrysler Pacifica (Minivens)', 'multiplier' => 1.6],
        ['name' => 'Chrysler Grand Voyager', 'label' => 'Chrysler Grand Voyager (Lielais minivens)', 'multiplier' => 1.7],
        ['name' => 'Alfa Romeo MiTo', 'label' => 'Alfa Romeo MiTo (Mazais auto)', 'multiplier' => 1.1],
        ['name' => 'Alfa Romeo Giulietta', 'label' => 'Alfa Romeo Giulietta (Hečbeks)', 'multiplier' => 1.2],
        ['name' => 'Alfa Romeo Giulia', 'label' => 'Alfa Romeo Giulia (Sporta sedans)', 'multiplier' => 1.3],
        ['name' => 'Alfa Romeo Stelvio', 'label' => 'Alfa Romeo Stelvio (SUV)', 'multiplier' => 1.4],
        ['name' => 'Alfa Romeo 159', 'label' => 'Alfa Romeo 159 (Vidējs sedans)', 'multiplier' => 1.3],
        ['name' => 'Alfa Romeo 147', 'label' => 'Alfa Romeo 147 (Kompakts)', 'multiplier' => 1.2],
        ['name' => 'Alfa Romeo 156', 'label' => 'Alfa Romeo 156 (Sedans)', 'multiplier' => 1.2],
        ['name' => 'Dacia Spring', 'label' => 'Dacia Spring (Elektro kompakts)', 'multiplier' => 1.1],
        ['name' => 'Dacia Sandero', 'label' => 'Dacia Sandero (Kompakts)', 'multiplier' => 1.1],
        ['name' => 'Dacia Logan', 'label' => 'Dacia Logan (Sedans/Universālis)', 'multiplier' => 1.2],
        ['name' => 'Dacia Jogger', 'label' => 'Dacia Jogger (7-vietīgs ģimenes auto)', 'multiplier' => 1.4],
        ['name' => 'Dacia Duster', 'label' => 'Dacia Duster (SUV)', 'multiplier' => 1.4],
        ['name' => 'Dacia Lodgy', 'label' => 'Dacia Lodgy (Ģimenes minivens)', 'multiplier' => 1.5],
        ['name' => 'Dacia Dokker', 'label' => 'Dacia Dokker (Mazais busiņš)', 'multiplier' => 1.5],
        ['name' => 'Land Rover Defender', 'label' => 'Land Rover Defender (Apvidus auto)', 'multiplier' => 1.6],
        ['name' => 'Land Rover Discovery', 'label' => 'Land Rover Discovery (Premium SUV)', 'multiplier' => 1.6],
        ['name' => 'Land Rover Discovery Sport', 'label' => 'Discovery Sport (Mazāks SUV)', 'multiplier' => 1.5],
        ['name' => 'Range Rover Evoque', 'label' => 'Range Rover Evoque (Mazais luksusa SUV)', 'multiplier' => 1.4],
        ['name' => 'Range Rover Velar', 'label' => 'Range Rover Velar (Luksusa SUV)', 'multiplier' => 1.5],
        ['name' => 'Range Rover Sport', 'label' => 'Range Rover Sport (Sporta SUV)', 'multiplier' => 1.6],
        ['name' => 'Range Rover', 'label' => 'Range Rover (Flagmanis SUV)', 'multiplier' => 1.7],
        ['name' => 'Jaguar XE', 'label' => 'Jaguar XE (Sedans)', 'multiplier' => 1.3],
        ['name' => 'Jaguar XF', 'label' => 'Jaguar XF (Lielais sedans)', 'multiplier' => 1.4],
        ['name' => 'Jaguar XJ', 'label' => 'Jaguar XJ (Luksusa sedans)', 'multiplier' => 1.5],
        ['name' => 'Jaguar F-Pace', 'label' => 'Jaguar F-Pace (SUV)', 'multiplier' => 1.5],
        ['name' => 'Jaguar E-Pace', 'label' => 'Jaguar E-Pace (Mazais SUV)', 'multiplier' => 1.4],
        ['name' => 'Jaguar I-Pace', 'label' => 'Jaguar I-Pace (Elektro SUV)', 'multiplier' => 1.5],
        ['name' => 'Jaguar F-Type', 'label' => 'Jaguar F-Type (Sporta kupeja/kabriolets)', 'multiplier' => 1.5],
        ['name' => 'Porsche 911', 'label' => 'Porsche 911 (Sporta kupeja)', 'multiplier' => 1.6],
        ['name' => 'Porsche 718 Cayman', 'label' => 'Porsche 718 Cayman (Kupeja)', 'multiplier' => 1.5],
        ['name' => 'Porsche 718 Boxster', 'label' => 'Porsche 718 Boxster (Kabriolets)', 'multiplier' => 1.5],
        ['name' => 'Porsche Panamera', 'label' => 'Porsche Panamera (Luksusa sedans)', 'multiplier' => 1.6],
        ['name' => 'Porsche Taycan', 'label' => 'Porsche Taycan (Elektro sedans)', 'multiplier' => 1.5],
        ['name' => 'Porsche Macan', 'label' => 'Porsche Macan (Mazais SUV)', 'multiplier' => 1.5],
        ['name' => 'Porsche Cayenne', 'label' => 'Porsche Cayenne (SUV)', 'multiplier' => 1.6],
        ['name' => 'Mini One', 'label' => 'Mini One (Mazais auto)', 'multiplier' => 1.0],
        ['name' => 'Mini Cooper', 'label' => 'Mini Cooper (Kompakts)', 'multiplier' => 1.1],
        ['name' => 'Mini Cooper S', 'label' => 'Mini Cooper S (Sporta kompakts)', 'multiplier' => 1.2],
        ['name' => 'Mini Clubman', 'label' => 'Mini Clubman (Hečbeks/Universālis)', 'multiplier' => 1.2],
        ['name' => 'Mini Countryman', 'label' => 'Mini Countryman (Mazais SUV)', 'multiplier' => 1.3],
        ['name' => 'Mini Electric', 'label' => 'Mini Electric (Elektro kompakts)', 'multiplier' => 1.2],
        ['name' => 'Smart Fortwo', 'label' => 'Smart Fortwo (2-vietīgs pilsētas auto)', 'multiplier' => 0.9],
        ['name' => 'Smart Forfour', 'label' => 'Smart Forfour (4-vietīgs kompakts)', 'multiplier' => 1.0],
        ['name' => 'Smart EQ Fortwo', 'label' => 'Smart EQ Fortwo (Elektro 2-vietīgs)', 'multiplier' => 1.0],
        ['name' => 'Smart EQ Forfour', 'label' => 'Smart EQ Forfour (Elektro kompakts)', 'multiplier' => 1.1],
        ['name' => 'Saab 9-3', 'label' => 'Saab 9-3 (Sedans/Kabriolets)', 'multiplier' => 1.2],
        ['name' => 'Saab 9-5', 'label' => 'Saab 9-5 (Lielais sedans)', 'multiplier' => 1.3],
        ['name' => 'Saab 9-7X', 'label' => 'Saab 9-7X (SUV)', 'multiplier' => 1.5],
        ['name' => 'Saab 900', 'label' => 'Saab 900 (Hečbeks/Klasika)', 'multiplier' => 1.1],
        ['name' => 'Daewoo Matiz', 'label' => 'Daewoo Matiz (Mazais pilsētas auto)', 'multiplier' => 1.0],
        ['name' => 'Daewoo Kalos', 'label' => 'Daewoo Kalos (Kompakts)', 'multiplier' => 1.1],
        ['name' => 'Daewoo Lanos', 'label' => 'Daewoo Lanos (Sedans)', 'multiplier' => 1.1],
        ['name' => 'Daewoo Nubira', 'label' => 'Daewoo Nubira (Sedans/Universālis)', 'multiplier' => 1.2],
        ['name' => 'Daewoo Leganza', 'label' => 'Daewoo Leganza (Lielāks sedans)', 'multiplier' => 1.3],
    ],
];
